### ISSUE TITLE
I2S_HAS_SET_BUFFER_SIZE never defined

### ISSUE THREAD

**Issue by tigoe** [arduino-libraries/ArduinoSound#17]
This constant wraps the setBufferSize function, but it's never defined in the library. Where is it defined?

**Comment by sandeepmistry** [comment]
It will be part of the next SAMD core release, here's the relevant change in the core: https://github.com/arduino/ArduinoCore-samd/commit/6802376ac85ae18f8c9baacd38c51db9c84a8ae3#diff-659e8f6da1f13cddd7bb35870f12a05d

**Comment by sandeepmistry** [comment]
Hi @tigoe, the 1.8.1 release of the SAMD core has this change.
