### ISSUE TITLE
DMAC Handler Error

### ISSUE THREAD

**Issue by dennischrist** [arduino-libraries/ArduinoSound#18]
Hi,

I tried compiling this on two differnt computers with both a Bluefruit M0 Feather as well as a ItsyBitsy M0.

In both cases I get this:

libraries/Adafruit_ZeroDMA/Adafruit_ZeroDMA.cpp.o: In function `DMAC_Handler':
Adafruit_ZeroDMA.cpp:(.text.DMAC_Handler+0x0): multiple definition of `DMAC_Handler'
libraries/I2S/utility/DMA.cpp.o:DMA.cpp:(.text.DMAC_Handler+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Adafruit Feather M0.

Any idea how to remedy this?

**Comment by sandeepmistry** [comment]
Hi @dennischrist,

Since I2S use DMA, the libraries are not compatible. I suggest you contact Adafruit support or forum to further resolve this.
