### ISSUE TITLE
Missing includes arm_math.h

### ISSUE THREAD

**Issue by Robert-Ernst** [arduino-libraries/ArduinoSound#4]
Arduino: 1.8.2 (Mac OS X), Board: "Arduino/Genuino Uno"

In file included from /Users/user/Documents/Arduino/sketch_apr26a/libraries/ArduinoSound-master/src/ArduinoSound.h:28:0,
                 from /Users/user/Git/audio_sensor/audio_library_test/audio_library_test.ino:1:
/Users/user/Documents/Arduino/sketch_apr26a/libraries/ArduinoSound-master/src/AmplitudeAnalyzer.h:25:22: fatal error: arm_math.h: No such file or directory
 #include <arm_math.h>
                      ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by facchinm** [comment]
Hi @BerndErnst , this library is only compatible with ARM boards (like Zero, MKR1000 etc), AVR boards (like UNO) miss the needed hardware peripherals.
