### ISSUE TITLE
2 x I2S microphones Stereo configuration

### ISSUE THREAD

**Issue by MathieuTT** [arduino-libraries/ArduinoSound#5]
Hi,
Thank you for this library.

I tried it with ICS-43432 and SPH0645 microphones and it works fine in MONO configuration.
I would like to use 2 of them in order to have a STEREO configuration :

![image](https://cloud.githubusercontent.com/assets/28043926/26679971/ad6611ec-46d7-11e7-9373-9212b6268655.png)

Is there a way to differentiate the data coming from Right and Left channel ?

Thank you for your time.
Best regards, Mathieu.

**Comment by sandeepmistry** [comment]
Hi @MathieuTT,

> Is there a way to differentiate the data coming from Right and Left channel ?

No there is not, the data from each channel will be interleaved when you read it.
