### ISSUE TITLE
How do you select a different set of pins? 

### ISSUE THREAD

**Issue by codegrue** [arduino-libraries/ArduinoSound#50]
.

**Comment by per1234** [comment]
Hi @codegrue. This library does not provide such a capability. It uses the [global `I2SClass` instance](https://github.com/arduino/ArduinoCore-samd/blob/1.8.14/libraries/I2S/src/I2S.cpp#L533) on the default I2S bus configured in the core and doesn't have any mechanism for the user to pass a different instance for use.

I am wondering about your question though. You must use the I2S bus pins. Even though it might be possible to [expose an I2S bus on pins](https://docs.arduino.cc/tutorials/communication/SamdSercom/) other than those configured in the core, this is something that would only be done by very advanced users in unusual and rare use cases. Have you actually configured an I2S bus on different pins?
