### ISSUE TITLE
WAVE file header issue

### ISSUE THREAD

**Issue by speccy88** [arduino-libraries/ArduinoSound#9]
ffmpeg on Linux adds a LIST section between fmt and data when converting an audio file to WAVE.

On the image below, you have the same file exported by ffmpeg on the left and Audacity on the right. 
![image](https://user-images.githubusercontent.com/2388736/40398765-b92399bc-5e07-11e8-8937-ea01f4413dd2.png)

WAVE file with the LIST section don't work with the library right now.

there is no easy way with ffmpeg to remove this metadata. Getting this to work would allow a lot more files to work correctly with the library.

**Comment by don** [comment]
When I add the `bitexact` flag, ffmpeg does not write the LIST-INFO header.

    say -o hello.aiff hello
    ffmpeg -i hello.aiff -bitexact -ac 2 hello.wav
